---
apiVersion: v1
kind: Service
metadata:
  name: "gauth-proxy-{{ .Values.appName }}-svc"
  namespace: "{{ .Values.namespace }}"
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: gauth-proxy
    tier: "{{ .Values.appName }}"
  type: NodePort